/*
 * This file is generated by jOOQ.
 */
package org.luffy.jooq.tables;


import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.luffy.jooq.Keys;
import org.luffy.jooq.ManageHotelV2;
import org.luffy.jooq.tables.records.RoomImagesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomImages extends TableImpl<RoomImagesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>manage_hotel_v2.room_images</code>
     */
    public static final RoomImages ROOM_IMAGES = new RoomImages();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomImagesRecord> getRecordType() {
        return RoomImagesRecord.class;
    }

    /**
     * The column <code>manage_hotel_v2.room_images.id</code>.
     */
    public final TableField<RoomImagesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>manage_hotel_v2.room_images.url</code>.
     */
    public final TableField<RoomImagesRecord, String> URL = createField(DSL.name("url"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>manage_hotel_v2.room_images.room_id</code>.
     */
    public final TableField<RoomImagesRecord, Integer> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.INTEGER, this, "");

    private RoomImages(Name alias, Table<RoomImagesRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoomImages(Name alias, Table<RoomImagesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>manage_hotel_v2.room_images</code> table
     * reference
     */
    public RoomImages(String alias) {
        this(DSL.name(alias), ROOM_IMAGES);
    }

    /**
     * Create an aliased <code>manage_hotel_v2.room_images</code> table
     * reference
     */
    public RoomImages(Name alias) {
        this(alias, ROOM_IMAGES);
    }

    /**
     * Create a <code>manage_hotel_v2.room_images</code> table reference
     */
    public RoomImages() {
        this(DSL.name("room_images"), null);
    }

    public <O extends Record> RoomImages(Table<O> child, ForeignKey<O, RoomImagesRecord> key) {
        super(child, key, ROOM_IMAGES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ManageHotelV2.MANAGE_HOTEL_V2;
    }

    @Override
    public Identity<RoomImagesRecord, Integer> getIdentity() {
        return (Identity<RoomImagesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RoomImagesRecord> getPrimaryKey() {
        return Keys.KEY_ROOM_IMAGES_PRIMARY;
    }

    @Override
    public RoomImages as(String alias) {
        return new RoomImages(DSL.name(alias), this);
    }

    @Override
    public RoomImages as(Name alias) {
        return new RoomImages(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomImages rename(String name) {
        return new RoomImages(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomImages rename(Name name) {
        return new RoomImages(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
