/*
 * This file is generated by jOOQ.
 */
package org.luffy.jooq;


import org.luffy.jooq.tables.FlywaySchemaHistory;
import org.luffy.jooq.tables.Users;


/**
 * Convenience access to all tables in manage_hotel_v2.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>manage_hotel_v2.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>manage_hotel_v2.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
