/*
 * This file is generated by jOOQ.
 */
package org.luffy.jooq;


import org.luffy.jooq.tables.BookedRooms;
import org.luffy.jooq.tables.Bookings;
import org.luffy.jooq.tables.Events;
import org.luffy.jooq.tables.FlywaySchemaHistory;
import org.luffy.jooq.tables.ImageUpload;
import org.luffy.jooq.tables.RoomImages;
import org.luffy.jooq.tables.Rooms;
import org.luffy.jooq.tables.Users;


/**
 * Convenience access to all tables in manage_hotel_v2.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>manage_hotel_v2.booked_rooms</code>.
     */
    public static final BookedRooms BOOKED_ROOMS = BookedRooms.BOOKED_ROOMS;

    /**
     * The table <code>manage_hotel_v2.bookings</code>.
     */
    public static final Bookings BOOKINGS = Bookings.BOOKINGS;

    /**
     * The table <code>manage_hotel_v2.events</code>.
     */
    public static final Events EVENTS = Events.EVENTS;

    /**
     * The table <code>manage_hotel_v2.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>manage_hotel_v2.image_upload</code>.
     */
    public static final ImageUpload IMAGE_UPLOAD = ImageUpload.IMAGE_UPLOAD;

    /**
     * The table <code>manage_hotel_v2.room_images</code>.
     */
    public static final RoomImages ROOM_IMAGES = RoomImages.ROOM_IMAGES;

    /**
     * The table <code>manage_hotel_v2.rooms</code>.
     */
    public static final Rooms ROOMS = Rooms.ROOMS;

    /**
     * The table <code>manage_hotel_v2.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
