/*
 * This file is generated by jOOQ.
 */
package org.luffy.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.luffy.jooq.tables.BookedRooms;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookedRoomsRecord extends UpdatableRecordImpl<BookedRoomsRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>manage_hotel_v2.booked_rooms.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>manage_hotel_v2.booked_rooms.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>manage_hotel_v2.booked_rooms.booking_id</code>.
     */
    public void setBookingId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>manage_hotel_v2.booked_rooms.booking_id</code>.
     */
    public Integer getBookingId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>manage_hotel_v2.booked_rooms.room_id</code>.
     */
    public void setRoomId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>manage_hotel_v2.booked_rooms.room_id</code>.
     */
    public Integer getRoomId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return BookedRooms.BOOKED_ROOMS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return BookedRooms.BOOKED_ROOMS.BOOKING_ID;
    }

    @Override
    public Field<Integer> field3() {
        return BookedRooms.BOOKED_ROOMS.ROOM_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getBookingId();
    }

    @Override
    public Integer component3() {
        return getRoomId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getBookingId();
    }

    @Override
    public Integer value3() {
        return getRoomId();
    }

    @Override
    public BookedRoomsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public BookedRoomsRecord value2(Integer value) {
        setBookingId(value);
        return this;
    }

    @Override
    public BookedRoomsRecord value3(Integer value) {
        setRoomId(value);
        return this;
    }

    @Override
    public BookedRoomsRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookedRoomsRecord
     */
    public BookedRoomsRecord() {
        super(BookedRooms.BOOKED_ROOMS);
    }

    /**
     * Create a detached, initialised BookedRoomsRecord
     */
    public BookedRoomsRecord(Integer id, Integer bookingId, Integer roomId) {
        super(BookedRooms.BOOKED_ROOMS);

        setId(id);
        setBookingId(bookingId);
        setRoomId(roomId);
    }
}
