/*
 * This file is generated by jOOQ.
 */
package org.luffy.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.luffy.jooq.tables.ImageUpload;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImageUploadRecord extends UpdatableRecordImpl<ImageUploadRecord> implements Record5<Integer, String, Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>manage_hotel_v2.image_upload.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>manage_hotel_v2.image_upload.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>manage_hotel_v2.image_upload.key_name</code>.
     */
    public void setKeyName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>manage_hotel_v2.image_upload.key_name</code>.
     */
    public String getKeyName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>manage_hotel_v2.image_upload.file_size</code>.
     */
    public void setFileSize(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>manage_hotel_v2.image_upload.file_size</code>.
     */
    public Integer getFileSize() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>manage_hotel_v2.image_upload.mimetype</code>.
     */
    public void setMimetype(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>manage_hotel_v2.image_upload.mimetype</code>.
     */
    public String getMimetype() {
        return (String) get(3);
    }

    /**
     * Setter for <code>manage_hotel_v2.image_upload.original_name</code>.
     */
    public void setOriginalName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>manage_hotel_v2.image_upload.original_name</code>.
     */
    public String getOriginalName() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Integer, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ImageUpload.IMAGE_UPLOAD.ID;
    }

    @Override
    public Field<String> field2() {
        return ImageUpload.IMAGE_UPLOAD.KEY_NAME;
    }

    @Override
    public Field<Integer> field3() {
        return ImageUpload.IMAGE_UPLOAD.FILE_SIZE;
    }

    @Override
    public Field<String> field4() {
        return ImageUpload.IMAGE_UPLOAD.MIMETYPE;
    }

    @Override
    public Field<String> field5() {
        return ImageUpload.IMAGE_UPLOAD.ORIGINAL_NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getKeyName();
    }

    @Override
    public Integer component3() {
        return getFileSize();
    }

    @Override
    public String component4() {
        return getMimetype();
    }

    @Override
    public String component5() {
        return getOriginalName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getKeyName();
    }

    @Override
    public Integer value3() {
        return getFileSize();
    }

    @Override
    public String value4() {
        return getMimetype();
    }

    @Override
    public String value5() {
        return getOriginalName();
    }

    @Override
    public ImageUploadRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ImageUploadRecord value2(String value) {
        setKeyName(value);
        return this;
    }

    @Override
    public ImageUploadRecord value3(Integer value) {
        setFileSize(value);
        return this;
    }

    @Override
    public ImageUploadRecord value4(String value) {
        setMimetype(value);
        return this;
    }

    @Override
    public ImageUploadRecord value5(String value) {
        setOriginalName(value);
        return this;
    }

    @Override
    public ImageUploadRecord values(Integer value1, String value2, Integer value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImageUploadRecord
     */
    public ImageUploadRecord() {
        super(ImageUpload.IMAGE_UPLOAD);
    }

    /**
     * Create a detached, initialised ImageUploadRecord
     */
    public ImageUploadRecord(Integer id, String keyName, Integer fileSize, String mimetype, String originalName) {
        super(ImageUpload.IMAGE_UPLOAD);

        setId(id);
        setKeyName(keyName);
        setFileSize(fileSize);
        setMimetype(mimetype);
        setOriginalName(originalName);
    }
}
