CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
name VARCHAR(255) NOT NULL,
address VARCHAR(255) NOT NULL,
phone VARCHAR(20) NOT NULL,
avatar VARCHAR(255) NULL,
role VARCHAR(45) NULL DEFAULT 'user',
PRIMARY KEY (id));